version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.13-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scribe
    restart: unless-stopped
