name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Beta - Test both PG17 and PG18
          - ha-version: "beta"
            python-version: "3.13"
            postgres-version: "pg18"
          - ha-version: "beta"
            python-version: "3.13"
            postgres-version: "pg17"

          # Stable - Test both PG17 and PG18
          - ha-version: "stable"
            python-version: "3.13"
            postgres-version: "pg18"
          - ha-version: "stable"
            python-version: "3.13"
            postgres-version: "pg17"

    services:
      timescaledb:
        image: timescale/timescaledb:latest-${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: scribe
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        
    - name: Install Home Assistant ${{ matrix.ha-version }}
      run: |
        if [ "${{ matrix.ha-version }}" == "stable" ]; then
          pip install homeassistant
        elif [ "${{ matrix.ha-version }}" == "beta" ]; then
          pip install --pre homeassistant
        else
          pip install homeassistant==${{ matrix.ha-version }}
        fi

    - name: Run Linting
      run: |
        ruff check .

    - name: Run Unit Tests
      run: |
        pytest tests --ignore=tests/test_integration.py

    - name: Run Integration Tests
      env:
        SCRIBE_INTEGRATION_TEST_DB_URL: postgresql://postgres:password@127.0.0.1:5432/scribe
      run: |
        pytest tests/test_integration.py
